#!/usr/bin/env python3
"""Compute this repo's stats and inject them into README.md between markers.

Run by .github/workflows/stats.yml on every push to main, once a day, and on
demand. Everything it writes is inside the markers, so hand-editing the rest of
the README is safe, and running it twice changes nothing.

Outputs:
  stats.json  a single-key file, because shields.io's /endpoint badge reads the
              first key and uses it as the badge text
  README.md   a table injected between the stats markers
"""

import json
import os
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / "java"
START = "<!-- stats:start -->"
END = "<!-- stats:end -->"

# `builtin()` dispatches on verb.equals("name"), so that is the source of truth
# for the command list. Anything that changes the dispatch changes the count.
BUILTIN_RE = re.compile(r'verb\.equals\("([A-Za-z0-9_.]+)"\)')


def line_stats(path: Path) -> tuple[int, int, int]:
    """Return (total, blank, comment) line counts for a Java file.

    Block comments are tracked so that a run of commented-out code is not
    quietly reported as live code.
    """
    total = blank = comment = 0
    in_block = False
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return 0, 0, 0

    for raw in text.splitlines():
        total += 1
        line = raw.strip()
        if not line:
            blank += 1
            continue
        if in_block:
            comment += 1
            if "*/" in line:
                in_block = False
            continue
        if line.startswith("/*"):
            comment += 1
            if "*/" not in line:
                in_block = True
            continue
        if line.startswith("//") or line.startswith("*"):
            comment += 1
            continue
    return total, blank, comment


def git(*args: str) -> str:
    try:
        out = subprocess.run(
            ("git",) + args,
            cwd=ROOT,
            capture_output=True,
            text=True,
            timeout=30,
        )
        return out.stdout.strip()
    except (OSError, subprocess.SubprocessError):
        return ""


def main() -> int:
    java_files = sorted(SRC.rglob("*.java")) if SRC.is_dir() else []
    if not java_files:
        print("no java sources found, refusing to write empty stats", file=sys.stderr)
        return 1

    per_file = []
    tot_total = tot_blank = tot_comment = 0
    for f in java_files:
        total, blank, comment = line_stats(f)
        code = total - blank - comment
        per_file.append((f.name, total, code))
        tot_total += total
        tot_blank += blank
        tot_comment += comment

    tot_code = tot_total - tot_blank - tot_comment

    activity = ""
    for f in java_files:
        try:
            activity += f.read_text(encoding="utf-8", errors="replace")
        except OSError:
            pass
    builtins = sorted(set(BUILTIN_RE.findall(activity)))

    res_files = (
        sum(1 for p in (ROOT / "res").rglob("*") if p.is_file())
        if (ROOT / "res").is_dir()
        else 0
    )
    commits = git("rev-list", "--count", "HEAD")
    contributors = len(
        [l for l in git("shortlog", "-sne", "HEAD").splitlines() if l.strip()]
    )
    branch = git("rev-parse", "--abbrev-ref", "HEAD") or "main"
    sha = git("rev-parse", "--short", "HEAD")
    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    table = [
        START,
        "",
        "| metric | count |",
        "| --- | ---: |",
        f"| lines of java | {tot_total:,} |",
        f"| lines of code | {tot_code:,} |",
        f"| comment + blank | {tot_blank + tot_comment:,} |",
        f"| source files | {len(java_files)} |",
        f"| shell builtins | {len(builtins)} |",
        f"| resource files | {res_files} |",
        f"| commits | {commits or '0'} |",
        f"| contributors | {contributors} |",
        "",
        "<details><summary>largest files</summary>",
        "",
        "| file | lines | code |",
        "| --- | ---: | ---: |",
    ]
    for name, total, code in sorted(per_file, key=lambda r: -r[1])[:6]:
        table.append(f"| `{name}` | {total:,} | {code:,} |")
    table += [
        "",
        "</details>",
        "",
        f"<sub>generated by `update_stats.py` on `{branch}` at `{sha}` &middot; {stamp}</sub>",
        END,
    ]
    block = "\n".join(table)

    readme = ROOT / "README.md"
    if not readme.is_file():
        print("README.md not found, wrote stats.json only", file=sys.stderr)
        wrote_readme = False
    else:
        text = readme.read_text(encoding="utf-8")
        if START in text and END in text:
            head, _, rest = text.partition(START)
            _, _, tail = rest.partition(END)
            new_text = head + block + tail
        else:
            # markers were deleted by hand, put the block back at the end
            new_text = text.rstrip() + "\n\n" + block + "\n"
        wrote_readme = new_text != text
        if wrote_readme:
            readme.write_text(new_text, encoding="utf-8", newline="\n")

    # shields.io /endpoint uses the first key as the badge text, so one key only
    stats_path = ROOT / "stats.json"
    stats_payload = json.dumps({"lines": f"{tot_total:,}"}, indent=2) + "\n"
    wrote_json = (
        not stats_path.is_file()
        or stats_path.read_text(encoding="utf-8") != stats_payload
    )
    if wrote_json:
        stats_path.write_text(stats_payload, encoding="utf-8", newline="\n")

    print(f"java lines   : {tot_total} ({tot_code} code)")
    print(f"files        : {len(java_files)}")
    print(f"builtins     : {len(builtins)}")
    print(f"res files    : {res_files}")
    print(f"commits      : {commits} from {contributors} contributor(s)")
    print(f"readme       : {'updated' if wrote_readme else 'already current'}")
    print(f"stats.json   : {'updated' if wrote_json else 'already current'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
